### ISSUE TITLE
Error: failed to find BLE beacon : can't dial: connection canceled

### ISSUE THREAD

**Issue by raphmur** [iainbullock/tesla_ble_mqtt_docker#14]
I got this error when trying to lock the car.
Note that I had the app opened at the same time, and not too far from the car...

```
Received MQTT message: tesla_ble/command lock
Command lock requested
Lock Car
Attempt 1/5
Error: failed to find BLE beacon for [VIN hidden] (Sdb4009e97649af12C): can't dial: can't dial: connection canceled
```

I think this error broke the loop in `send_command`... Any idea?

**Comment by iainbullock** [comment]
Interesting that it broke the loop. I'm thinking the set +e directive gets cancelled after run.sh calls the scripts containing the subroutines. It worked when all the subs were in run.sh. I will have to read up on set +e and see if that explains the loop getting broken

**Comment by raphmur** [comment]
Okay I managed to set a workaround.
In fact I was using `set -e` in the HA integration code.

I changed to this:

```
send_command() {
 for i in $(seq 5); do
  echo "Attempt $i/5"
  set +e
  tesla-control -ble -vin $TESLA_VIN -key-name /share/tesla_ble_mqtt/private.pem -key-file /share/tesla_ble_mqtt/private.pem $1
  EXIT_STATUS=$?
  set -e
  if [ $EXIT_STATUS -eq 0 ]; then
    echo "Ok"
    break
  else
    echo "Error calling tesla-control: $EXIT_STATUS"
  fi
  sleep $SEND_CMD_RETRY_DELAY
 done 
}
```

**Comment by iainbullock** [comment]
Yours is probably a better approach so other errors get picked up. Can we close this one?
