### ISSUE TITLE
Reconnection to the broker after each message

### ISSUE THREAD

**Issue by MasterATM** [iainbullock/tesla_ble_mqtt_docker#7]
Hello,
First, thanks for your code. My charging automation is saved and it was straightforward to use :-)

I noticed that the client always disconnects and reconnects to the MQTT broker. After looking into the code, it might be due to the `-E` flag of mosquitto_sub. When used, the client disconnects after the subscription is acknowledged by the broker.

If I remove the flag and move `listen_to_mqtt` outside of the `while true` loop, then it still works fine and there are no more disconnection/reconnection. But then, I believe some error handling must be done in case mosquitto_sub has a problem and is killed. It must be respawned again.

What is your opinion?

Thanks.

**Comment by iainbullock** [comment]
Hello, thanks for your comments. 

Did you install the 'dev' branch version, as I didn't use the -E flag in the 'main' branch version?

I'm using the E flag to deliberately break the connection so I can also use bluetoothctl to scan for presence of the car. The manual https://mosquitto.org/man/mosquitto_sub-1.html says to use -E and -c together to create what it calls a 'durable client' session.

Is there a disadvantage of the constant connection / disconnection? If so I might have to have a rethink how to achieve the presence detection which was requested by other user (and something I will find useful too). I did consider spawning a separate process for the presence detection, but the two processes will try to access the bluetooth at the same time (which may or may not cause a problem)

Thanks

**Comment by MasterATM** [comment]
Hello,
Indeed, I was using the dev branch (for the wakeup call which works fine btw). Sorry for not mentioning it.

No, I had no problem with the constant connection/disconnection, I just found it strange to see the behavior in the MQTT server logs. Ok, I now understand your concerns with the presence detection, it makes sense.
I guess we can close this ticket.


Thanks again for the code which arrives at the perfect moment!
